site_name: 'Convert-Pheno-UI Documentation'
site_description: 'Convert-Pheno Toolbox Documentation'
site_author: 'Ivo Christopher Leist'
copyright: '&copy; Copyright 2023, Ivo Christopher Leist, CNAG'
repo_name: 'Convert-Pheno-UI'
repo_url: https://github.com/CNAG-Biomedical-Informatics/convert-pheno-ui
edit_uri: edit/main/docs/

extra_css: [css/theme_overrides.css]

plugins:
  - search
  - macros
  - mermaid2

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.superfences
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: beacon-v2
    # - pymdownx.emoji:
    #       emoji_index: !!python/name:materialx.emoji.twemoji
    #       emoji_generator: !!python/name:materialx.emoji.to_svg
    # - pymdownx.superfences:
    #     custom_fences:
    #         - name: mermaid
    #           class: mermaid
    #           format: !!python/name:mermaid2.fence_mermaid

nav:
  - Introduction:
      - What is Convert-Pheno-UI?: what-is-convert-pheno-ui.md
      - Accepted input formats: accepted-input-formats.md
      - Supported output formats: supported-output-formats.md
  - Use:
      - Playground: web-app.md
      - Playground-API: api.md
      - Run locally: run-locally.md
  - Self-hosting:
      - Prepare the host environment: host-environment.md
      - Deployment: deployment.md
  - Help:
      - Tutorial: tutorial.md
      - FAQs: faq.md
      - Future plans: future-plans.md
  - About:
      - About: about.md
      - Citation: citation.md

theme:
  name: material
  #custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: img/CP-logo-grey.png
  icon:
      repo: fontawesome/brands/github-alt
  features:
        - content.tabs.link
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/genomebeacons
    - icon: fontawesome/brands/github
      link: https://github.com/CNAG-Biomedical-Informatics/convert-pheno-ui

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
