name: Automated testing
title: 'Sweep: '
description: Write something like "Add the following additional tests to the api endpoint/client: ..."
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: We need tests for the following functionalities:...
