#
#   Docker compose for running containerized development environment
#
#   This file is part of convert-pheno-ui
#
#   Last modified: Dec/08/2023
#
#   Copyright (C) 2022-2023 Ivo Christopher Leist - CNAG (Ivo.leist@cnag.eu)
#
#   License: GPL-3.0 license

version: '3.3'
services:
  # api:
  #   image: leistivo/convert-pheno-ui-server:${DOCKER_IMG_TAG}
  #   # build:
  #   #   context: .
  #   #   target: prod
  #   #   args:
  #   #     - IGNORE_CACHE_FROM_HERE=${IGNORE_CACHE_FROM_HERE}
  #   depends_on:
  #     - db
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - .env
  #   tty: true
  #   volumes:
  #     - ./data:/data

  # db:
  #   image: postgres:13-alpine
  #   container_name: convert-pheno-api-db
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=${API_DB_NAME}
  #     - POSTGRES_USER=${API_DB_USER}
  #     - POSTGRES_PASSWORD=${API_DB_PW}
  #   restart: unless-stopped
  #   healthcheck:
  #     test: pg_isready -U postgres

  # run below for local development
  # make sure to run it from the root of this folder
  # so that the data folder is mounted correctly
  convert-pheno:
    user: ${UID}
    image: manuelrueda/convert-pheno:0.15
    container_name: convert-pheno-container
    restart: unless-stopped
    tty: true
    volumes:
      - api-data:/home

volumes:
  postgres-data:
  api-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
