{% set version = "0.10" %}

package:
  name: perl-convert-pheno
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MR/MRUEDA/Convert-Pheno-{{version}}.tar.gz
  sha256: 3560cdaed857196bc2520c79cbe73c6e0e6d370eda6b5cc2270fd5bfe4b52b6f

build:
  number: 0
  
requirements:
  build: 
    - {{ compiler('c') }}
    - make
  host:
    - perl
    - perl-app-cpanminus
    - perl-dbi
    - perl-dbd-sqlite
    # - perl-file-sharedir-install
    - perl-json-xs
    - perl-perlio-gzip
    - perl-sort-naturally
    - perl-test-exception
    - perl-test-warn
  run:
    - perl
    - perl-dbi
    - perl-dbd-sqlite
    - perl-json-xs
    - perl-perlio-gzip
    - perl-sort-naturally
  
test:
  # Perl 'use' tests
  imports:
    - Convert::Pheno
  commands:
    - convert-pheno -version

about:
  home: https://github.com/CNAG-Biomedical-Informatics/convert-pheno
  license: Artistic License 2.0
  summary: A software toolkit for the interconversion of standard data models for phenotypic data
  doc_url: https://cnag-biomedical-informatics.github.io/convert-pheno