name: Codecov
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./convertPheno_server/tests/reports/coverage/coverage.xml, ./convertPheno_client/cypress/coverage/lcov.info
