name: conda-build-perl-convert-pheno
on:
  workflow_dispatch:







jobs:
  ubuntu:
    name: ubuntu
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: build-linux-env

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('conda_recipe/environment.yaml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if conda_recipe/environment.yaml has not changed
          CACHE_NUMBER: 0
        id: cache

      - shell: bash -el {0}
        run: |
          mamba info
          mamba list
          mamba config --show-sources
          mamba config --show
          printenv | sort

      - name: Run mamba build 
        shell: bash -el {0}
        run: |
          mamba build conda_recipe
        
