name: Docker build server

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image of the server                 
      run: docker build -t leistivo/convert-pheno-ui-server:latest --target prod -f ./convertPheno_server
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push server to Docker Hub
      run: docker image push leistivo/convert-pheno-ui-server:latest
