name: Docker build client

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Scan Docker image
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: leistivo/convert-pheno-ui-client:latest
          args: --file=convertPheno_client/Dockerfile --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF to Snyk
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     context: convertPheno_client
      #     push: true
      #     tags: leistivo/convert-pheno-ui-client:latest
