name: Snyk server scan

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r convertPheno_server/requirements.txt
      - name: Run Snyk in convertPheno_server
        uses: snyk/actions/python-3.8@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: -d --file=/github/workspace/convertPheno_server/requirements.txt --sarif-file-output=/github/workspace/snyk.sarif

      - name: List all files
        run: ls -l ${{ github.workspace }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}
