name: Snyk Security

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r convertPheno_server/requirements.txt
      - name: Run Snyk in convertPheno_server
        uses: snyk/actions/python-3.8@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=convertPheno_server/requirements.txt -d --sarif-file-output=snyk.py.sarif

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: false
              cwd: convertPheno_client
              args: ["--frozen-lockfile", "--production"]

      - name: Run Snyk in convertPheno_client
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: convertPheno_client --sarif-file-output=snyk.node.sarif -d

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "/"
