name: ssl-cert-check

on:
  workflow_dispatch:

# on:
#   # Triggers the workflow every day at 8.00 UTC minutes
#   schedule:
#     - cron:  '0 8 * * *'

env:
  NODE_VERSION: 12.x

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check the health and certificate date for the specified URL(s)
        uses: padurean/https-certificate-expiry-health-check-action@v1.0.0
        with:
          # Check the following URLs
          url: https://convert-pheno.cnag.cat/
